this_fiber.forbid_suspend()
this_fiber.forbid_suspend()
this_fiber.forbid_suspend()
this_fiber.forbid_suspend()

this_fiber.allow_suspend()
this_fiber.allow_suspend()
this_fiber.allow_suspend()
this_fiber.allow_suspend()
this_fiber.allow_suspend()
