local json = require('json')

local x = json.decode('[]')
print(type(x))
print(json.is_array(x))
print(#x)
print('--')

x = json.decode('[[]]')
print(type(x))
print(json.is_array(x))
print(#x)
print(json.is_array(x[1]))
print(#x[1])
print('--')

x = json.decode('[[{}]]')
print(type(x))
print(json.is_array(x))
print(#x)
print(json.is_array(x[1]))
print(#x[1])
print(type(x[1][1]))
print(json.is_array(x[1][1]))
print('--')

x = json.decode('[[{}, "test"]]')
print(type(x))
print(json.is_array(x))
print(#x)
print(json.is_array(x[1]))
print(#x[1])
print(type(x[1][1]))
print(json.is_array(x[1][1]))
print(x[1][2])
print('--')

x = json.decode('[[{}], "test"]')
print(type(x))
print(json.is_array(x))
print(#x)
print(json.is_array(x[1]))
print(#x[1])
print(type(x[1][1]))
print(json.is_array(x[1][1]))
print(x[2])
print('--')

x = json.decode('[33, [44, 55, 66, 77]]')

print('type', type(x))
print('is_array', json.is_array(x))
print('val', x)
print('len', #x)
print('1', x[1])
print('2', x[2])

print('2.type', type(x[2]))
print('2.is_array', json.is_array(x[2]))
print('2.len', #x[2])
print('2.1', x[2][1])
print('2.2', x[2][2])
print('2.3', x[2][3])
print('2.3', x[2][4])
