= Emilua

:_:
:cpp: C++

A cross-platform execution engine for LuaJIT with support for async IO and
flexible threading layout.

Features:

* Complete fiber API (sync primitives, interruption API, clean-up handlers,
  fiber local storage, assert-like scheduling constraints, ...).
* TCP, UDP, TLS, file IO, address/service forward/reverse name resolution, UNIX
  domain sockets, SCM_RIGHTS fd-passing, pipes, serial ports, ...
* Clocks & timers.
* Filesystem API.
* Portable error comparison.
* Integrates with Lua builtins (i.e. you can mix up fibers and coroutines,
  modules, ...).
* Experimental support for HTTP & WebSocket.
* Actor API (each VM is an actor and they're spawned in thread pools under your
  control{_}footnote:[The default profile inherits the parent execution context
  (no new thread is created), but the option to create a new one is also
  available.]). You can even spawn isolated actors into new Linux namespaces.
* Native JSON module.
* Cross-platform (should run anywhere Boost.Asio also runs).

== Install

* https://aur.archlinux.org/packages/emilua/[ArchLinux].
* https://guix.gnu.org/[GUIX]: Emilua is available from the main repository.

== LICENSE

* C/{cpp} source code under Boost Software License.
* Lua code (including snippets scattered through the documentation) distributed
  in this repo is released as public domain.
* The file `src/emilua_gperf.awk` is released as public domain.
* Documentation (except for the source code samples contained within) is
  licensed under the Creative Commons Attribution 4.0 International License.
* Submodules and dependencies have their own licensing terms.

== Documentation

You can browse the documentation online at <https://docs.emilua.org/>.

Alternatively, you may pass `-Denable_manpages=true` when building the project
to have the documentation installed as manpages in your system. The reference
pages will be installed in the section `3em` ("em" stands for Emilua
Module). Tutorial pages will be installed in section 7, but every page in this
section will be prefixed by "emilua-".

== Dependencies

* Meson 0.62.0 or later.
* {cpp}20 compiler (GCC 12.1 or newer should work).
* LuaJIT.
* Boost.Asio (and other Boost libraries as well).
* https://fmt.dev/[fmt] 8.0 or later.
* `re2c` 1.3 or later.
* `gperf` 3.1 or later (maybe it'll work on older versions as well).
* GNU AWK 5.1 or later.
* `xxd`.

== Optional dependencies

* Curses: coloured output on errors.
* asciidoctor: manpages.
* asciidoctor-diagram: ascii-art diagrams for manpages.
* PlantUML: ascii-art diagrams for manpages.

== BUILD

[source]
----
$ mkdir build
$ cd build
$ meson ..
$ ninja
# ninja install
----

You can also pass options when you invoke `meson`. One of the options is `-D
enable_http=true`.

It's encouraged that you build luajit with `-DLUAJIT_ENABLE_LUA52COMPAT`.

== Tests

[source]
----
$ ninja test
----

You also need to have GNU AWK installed to run the tests.

Some tests are more intrusive and can only be built if you enable the plugins
support.

Some fuzz tests are also available. You can configure the seed for these tests
by setting the `EMILUA_TEST_SEED` environment variable. The envirnoment variable
`EMILUA_TEST_FUZZER_NITER` can be used to override the number of iterations.
