+++
title = "ip.tcp.socket"
+++

For now this is just an opaque type to be used elsewhere. Later down the road
there will be a proper binding for this Boost.Asio abstraction. However we need
to design a byte span Lua type before we get there.

[source,lua]
----
-- `socket_pair()` implementation is
-- left as an exercise for the reader
local a, b = socket_pair()

spawn(function()
    local buf = byte_span.new(1024)
    local nread = b:read_some(buf)
    print(buf:slice(1, nread))
end):detach()

local nwritten = a:write(byte_span.append('Hello World'))
print(nwritten)
----

== Functions

=== `new() -> ip.tcp.socket`

Constructor.

=== `connect(self, addr: ip.address, port: number)`

Initiate a connect operation and blocks current fiber until it completes or
errs.

=== `read_some(self, buffer: byte_span) -> number`

Read data from the stream socket and blocks current fiber until it completes or
errs.

Returns the number of bytes read.

=== `write_some(self, buffer: byte_span) -> number`

Write data to the stream socket and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

=== `write(self, buffer: byte_span) -> number`

Write all of the supplied data to the stream socket and blocks current fiber
until it completes or errs.

Returns the ``buffer``'s size (number of bytes written).

https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/async_write/overload1.html[As
in Boost.Asio]:

[quote]
____
This operation is implemented in terms of zero or more calls to the stream's
async_write_some function, and is known as a _composed operation_. The program
must ensure that the stream performs no other write operations (such as
async_write, the stream's async_write_some function, or any other composed
operations that perform writes) until this operation completes.
____

=== `set_option(self, opt: string, val)`

Set an option on the socket.

Currently available options are:

`"no_delay"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/ip__tcp/no_delay.html[Check
Boost.Asio documentation].

`"send_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_low_watermark.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_low_watermark.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"out_of_band_inline"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/out_of_band_inline.html[Check
Boost.Asio documentation].

`"linger"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/linger.html[Check
Boost.Asio documentation].

`"keep_alive"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/keep_alive.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the socket.

Currently available options are:

`"no_delay"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/ip__tcp/no_delay.html[Check
Boost.Asio documentation].

`"send_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_low_watermark.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_low_watermark.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"out_of_band_inline"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/out_of_band_inline.html[Check
Boost.Asio documentation].

`"linger"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/linger.html[Check
Boost.Asio documentation].

`"keep_alive"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/keep_alive.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].
