+++
title = "ip.udp.socket"
+++

[source,lua]
----
local sock = ip.udp.socket.new()
sock.open('v4')

spawn(function()
    local buf = byte_span.new(1024)
    local nread = b:read_some(buf)
    print(buf:slice(1, nread))
end):detach()

local nwritten = a:write(byte_span.append('Hello World'))
print(nwritten)
----

== Functions

=== `new() -> ip.udp.socket`

Constructor.

=== `open(self, address_family: string|ip.address)`

Open the socket.

`address_family` can be either `"v4"` or `"v6"`. If you provide an `ip.address`
object, the appropriate value will be inferred.

=== `bind(self, addr: ip.address|string, port: number)`

Bind the socket to the given local endpoint.

=== `connect(self, addr: ip.address, port: number)`

Set the default destination address so datagrams can be sent using `send()` or
`write()` without specifying a destination address.

=== `close(self)`

Close the socket.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_datagram_socket/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous send, receive or connect operations will be cancelled
immediately, and will complete with the `boost::asio::error::operation_aborted`
error.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_datagram_socket/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error.
____

=== `receive(self, buffer: byte_span[, flags: number]) -> number, ip.address, number`

Receive a datagram and blocks current fiber until it completes or errs.

Returns the number of bytes read plus the endpoint (address {plus} port) of the
remote sender of the datagram.

`flags` is `0` or an or-combination of values from
link:../ip.message_flag/[`ip.message_flag`].

=== `send(self, buffer: byte_span[, flags: number]) -> number`

Send data on the datagram socket and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

`flags` is `0` or an or-combination of values from
link:../ip.message_flag/[`ip.message_flag`].

NOTE: The `send` operation can only be used with a connected socket. Use the
`send_to` function to send data on an unconnected datagram socket.

=== `send_to(self, buffer: byte_span, remote_addr: ip.address, remote_port: number[, flags: number]) -> number`

Send a datagram to the specified remote endpoint and blocks current fiber until
it completes or errs.

Returns the number of bytes written.

`flags` is `0` or an or-combination of values from
link:../ip.message_flag/[`ip.message_flag`].

=== `set_option(self, opt: string, val)`

Set an option on the socket.

Currently available options are:

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"broadcast"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/broadcast.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"reuse_address"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/reuse_address.html[Check
Boost.Asio documentation].

`"multicast_loop"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_enable_loopback.html[Check
Boost.Asio documentation].

`"multicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_hops.html[Check
Boost.Asio documentation].

`"join_multicast_group"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_join_group.html[Check
Boost.Asio documentation].

`"leave_multicast_group"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_leave_group.html[Check
Boost.Asio documentation].

`"multicast_interface"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_outbound_interface.html[Check
Boost.Asio documentation].

`"unicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_unicast%5F_hops.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the socket.

Currently available options are:

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"broadcast"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/broadcast.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"reuse_address"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/reuse_address.html[Check
Boost.Asio documentation].

`"multicast_loop"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_enable_loopback.html[Check
Boost.Asio documentation].

`"multicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_hops.html[Check
Boost.Asio documentation].

`"unicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_unicast%5F_hops.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

=== `io_control(self, command: string[, ...])`

Perform an IO control command on the socket.

Currently available commands are:

`"bytes_readable"`:: Expects no arguments. Get the amount of data that can be
read without blocking. Implements the `FIONREAD` IO control command.

== Properties

=== `is_open: boolean`

Whether the socket is open.

=== `local_address: ip.address`

The local address endpoint of the socket.

=== `local_port: number`

The local port endpoint of the socket.

=== `remote_address: ip.address`

The remote address endpoint of the socket.

=== `remote_port: number`

The remote port endpoint of the socket.
