= file.stream

== Functions

=== `new() -> file.stream`

Constructor.

=== `open(self, path: string, flags: number)`

Open the file using the specified path.

`flags` is an or-combination of values from
link:../file.open_flag/[`file.open_flag`].

=== `close(self)`

Close the file.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_stream_file/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous read or write operations will be cancelled immediately, and
will complete with the `boost::asio::error::operation_aborted` error.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the file.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_stream_file/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous read and write operations to
finish immediately, and the handlers for cancelled operations will be passed the
`boost::asio::error::operation_aborted` error.
____

=== `resize(self, n: number)`

Alter the size of the file.

This function resizes the file to the specified size, in bytes. If the current
file size exceeds n then any extra data is discarded. If the current size is
less than n then the file is extended and filled with zeroes

=== `seek(self, offset: number, whence: string) -> number`

Sets and gets the file position, measured from the beginning of the file, to the
position given by `offset` plus a base specified by the string `whence`, as
follows:

`set`:: Seek to an absolute position.
`cur`:: Seek to an offset relative to the current file position.
`end`:: Seek to an offset relative to the end of the file.

Returns the final file position, measured in bytes from the beginning of the
file.

IMPORTANT: Lua conventions on index starting at `1` are ignored. Indexes here
are OS-mandated and start at `0`.

=== `read_some(self, buffer: byte_span) -> number`

Read data from the stream file and blocks current fiber until it completes or
errs.

Returns the number of bytes read.

=== `write_some(self, buffer: byte_span) -> number`

Write data to the stream file and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

== Properties

=== `is_open: boolean`

Whether the file is open.

=== `size: number`

The size of the file.
