= ip

== Types

* link:../ip.address/[`address`].

== Modules

=== `tcp`

Has the following types:

* link:../ip.tcp.socket/[`socket`].
* link:../ip.tcp.acceptor/[`acceptor`].

==== Functions

===== `get_address_info(host: string|ip.address, service: string|number[, flags: number]) -> table`

[source,lua]
----
get_address_info()
get_address_v4_info()
get_address_v6_info()
----

Forward-resolves host and service into a list of endpoint entries. Current fiber
is suspended until operation finishes.

`flags` is `0` or an or-combination of values from
link:../ip.address_info_flag/[`ip.address_info_flag`].

NOTE: If no `flags` are passed to this function (i.e. `flags` is `nil`) then
this function will follow the glibc defaults even on non-glibc systems:
`bit.bor(address_configured,v4_mapped)`.

Returns a list of entries. Each entry will be a table with the following
members:

* `address: ip.address`.
* `port: number`.
* `host_name: string`.
* `service_name: string`.

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/ip__basic_resolver/async_resolve/overload3.html[More
info on Boost.Asio documentation].

If `host` is an `ip.address` then no host name resolution should be attempted.

If `service` is a number then no service name resolution should be attempted.

===== `get_name_info(a: ip.address, port: number) -> table`

Reverse-resolves the endpoint into a list of endpoint entries. Current fiber is
suspended until operation finishes.

Returns a list of entries. Each entry will be a table with the following
members:

* `address: ip.address`.
* `port: number`.
* `host_name: string`.
* `service_name: string`.

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/ip__basic_resolver/async_resolve/overload6.html[More
info on Boost.Asio documentation].

=== `udp`

Has the following types:

* link:../ip.udp.socket/[`socket`].

==== Functions

===== `get_address_info(host: string|ip.address, service: string|number[, flags: number]) -> table`

[source,lua]
----
get_address_info()
get_address_v4_info()
get_address_v6_info()
----

Forward-resolves host and service into a list of endpoint entries. Current fiber
is suspended until operation finishes.

`flags` is `0` or an or-combination of values from
link:../ip.address_info_flag/[`ip.address_info_flag`].

NOTE: If no `flags` are passed to this function (i.e. `flags` is `nil`) then
this function will follow the glibc defaults even on non-glibc systems:
`bit.bor(address_configured,v4_mapped)`.

Returns a list of entries. Each entry will be a table with the following
members:

* `address: ip.address`.
* `port: number`.
* `host_name: string`.
* `service_name: string`.

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/ip__basic_resolver/async_resolve/overload3.html[More
info on Boost.Asio documentation].

If `host` is an `ip.address` then no host name resolution should be attempted.

If `service` is a number then no service name resolution should be attempted.

===== `get_name_info(a: ip.address, port: number) -> table`

Reverse-resolves the endpoint into a list of endpoint entries. Current fiber is
suspended until operation finishes.

Returns a list of entries. Each entry will be a table with the following
members:

* `address: ip.address`.
* `port: number`.
* `host_name: string`.
* `service_name: string`.

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/ip__basic_resolver/async_resolve/overload6.html[More
info on Boost.Asio documentation].

=== Other modules

* link:../ip.address_info_flag/[`address_info_flag`].

== Functions

=== `host_name() -> string`

Get the current host name.
