= ip.get_address_info

ifeval::[{doctype} == manpage]

== NAME

Emilua - Lua execution engine

endif::[]

== Synopsis

[source,lua]
----
local ip = require "ip"

ip.tcp.get_address_info()
ip.tcp.get_address_v4_info()
ip.tcp.get_address_v6_info()
ip.udp.get_address_info()
ip.udp.get_address_v4_info()
ip.udp.get_address_v6_info()

function(host: string|ip.address, service: string|number[, flags: number]) -> table
----

== Description

Forward-resolves host and service into a list of endpoint entries. Current fiber
is suspended until operation finishes.

`flags` is `0` or an or-combination of values from
link:../ip.address_info_flag/[`ip.address_info_flag`].

NOTE: If no `flags` are passed to this function (i.e. `flags` is `nil`) then
this function will follow the glibc defaults even on non-glibc systems:
`bit.bor(address_configured,v4_mapped)`.

Returns a list of entries. Each entry will be a table with the following
members:

* `address: ip.address`.
* `port: number`.
* `host_name: string`.
* `service_name: string`.

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/ip__basic_resolver/async_resolve/overload3.html[More
info on Boost.Asio documentation].

If `host` is an `ip.address` then no host name resolution should be attempted.

If `service` is a number then no service name resolution should be attempted.
