= ip.tcp.socket

ifeval::[{doctype} == manpage]

== NAME

Emilua - Lua execution engine

== SYNOPSIS

endif::[]

[source,lua]
----
-- `socket_pair()` implementation is
-- left as an exercise for the reader
local a, b = socket_pair()

spawn(function()
    local buf = byte_span.new(1024)
    local nread = b:read_some(buf)
    print(buf:slice(1, nread))
end):detach()

local nwritten = stream.write(a, byte_span.append('Hello World'))
print(nwritten)
----

== Functions

=== `new() -> ip.tcp.socket`

Constructor.

=== `open(self, address_family: string|ip.address)`

Open the socket.

`address_family` can be either `"v4"` or `"v6"`. If you provide an `ip.address`
object, the appropriate value will be inferred.

=== `bind(self, addr: ip.address|string, port: number)`

Bind the socket to the given local endpoint.

=== `close(self)`

Close the socket.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_stream_socket/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous send, receive or connect operations will be cancelled
immediately, and will complete with the `boost::asio::error::operation_aborted`
error.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_stream_socket/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error.
____

=== `io_control(self, command: string[, ...])`

Perform an IO control command on the socket.

Currently available commands are:

`"bytes_readable"`:: Expects no arguments. Get the amount of data that can be
read without blocking. Implements the `FIONREAD` IO control command.

=== `shutdown(self, what: string)`

Disable sends or receives on the socket.

`what` can be one of the following:

`"receive"`:: Shutdown the receive side of the socket.
`"send"`:: Shutdown the send side of the socket.
`"both"`:: Shutdown both send and receive on the socket.

=== `connect(self, addr: ip.address, port: number)`

Initiate a connect operation and blocks current fiber until it completes or
errs.

=== `read_some(self, buffer: byte_span) -> number`

Read data from the stream socket and blocks current fiber until it completes or
errs.

Returns the number of bytes read.

=== `write_some(self, buffer: byte_span) -> number`

Write data to the stream socket and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

=== `receive(self, buffer: byte_span, flags: number) -> number`

Read data from the stream socket and blocks current fiber until it completes or
errs.

Returns the number of bytes read.

`flags` is `0` or an or-combination of values from
link:../ip.message_flag/[`ip.message_flag`].

=== `send(self, buffer: byte_span, flags: number) -> number`

Write data to the stream socket and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

`flags` is `0` or an or-combination of values from
link:../ip.message_flag/[`ip.message_flag`].

=== `send_file(self, file: file.random_access, offset: number, size_in_bytes: number, n_number_of_bytes_per_send: number[, head: byte_span[, tail: byte_span]]) -> number`

A wrapper for the
https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile[`TransmitFile()`
function].

NOTE: Only available on Windows.

IMPORTANT: Lua conventions on index starting at `1` are ignored. Indexes here
are OS-mandated and start at `0`.

=== `wait(self, wait_type: string)`

Wait for the socket to become ready to read, ready to write, or to have pending
error conditions.

In short, the reactor model is exposed on top of the proactor model.

IMPORTANT: You shouldn't be using reactor-style operations on Emilua. However
there's this one obsolete and buggy TCP feature that presumes reactor-style
operations: `SO_OOBINLINE` (`out_of_band_inline`) + `sockatmark()`
(`at_mark`). If you're implementing
http://www.tcpipguide.com/free/t_TelnetInterruptHandlingUsingOutOfBandSignalingTheT.htm[an
ancient obscure protocol] that for some reason can avoid the TCP OOB bugs then
you'll need to use this function.

`wait_type` can be one of the following:

`"read"`:: Wait for a socket to become ready to read.
`"write"`:: Wait for a socket to become ready to write.
`"error"`:: Wait for a socket to have error conditions pending.

=== `set_option(self, opt: string, val)`

Set an option on the socket.

Currently available options are:

`"tcp_no_delay"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/ip__tcp/no_delay.html[Check
Boost.Asio documentation].

`"send_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_low_watermark.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_low_watermark.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"out_of_band_inline"`::
Socket option for putting received out-of-band data inline.
+
IMPORTANT: Do bear in mind that
http://www.serverframework.com/asynchronousevents/2011/10/out-of-band-data-and-overlapped-io.html[the
BSD socket API for `SO_OOBINLINE` is incompatible with proactor-style
operations.]

`"linger"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/linger.html[Check
Boost.Asio documentation].

`"keep_alive"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/keep_alive.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the socket.

Currently available options are:

`"tcp_no_delay"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/ip__tcp/no_delay.html[Check
Boost.Asio documentation].

`"send_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_low_watermark.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_low_watermark"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_low_watermark.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"out_of_band_inline"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/out_of_band_inline.html[Check
Boost.Asio documentation].

`"linger"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/linger.html[Check
Boost.Asio documentation].

`"keep_alive"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/keep_alive.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

== Properties

=== `is_open: boolean`

Whether the socket is open.

=== `local_address: ip.address`

The local address endpoint of the socket.

=== `local_port: number`

The local port endpoint of the socket.

=== `remote_address: ip.address`

The remote address endpoint of the socket.

=== `remote_port: number`

The remote port endpoint of the socket.

=== `at_mark: boolean`

Whether the socket is at the out-of-band data mark.

IMPORTANT: You must set the `out_of_band_inline` socket option and use
reactor-style operations (`wait()`) to use this feature.
