= ip.tcp.acceptor

[source,lua]
----
local a = ip.tcp.acceptor.new()
a:open('v4')
a:set_option('reuse_address', true)
a:bind('127.0.0.1', 8080)
a:listen()

while true do
    local s = a:accept()
    spawn(function()
        my_client_handler(s)
    end)
end
----

== Functions

=== `new() -> ip.tcp.acceptor`

Constructor.

=== `open(self, address_family: string|ip.address)`

Open the acceptor.

`address_family` can be either `"v4"` or `"v6"`. If you provide an `ip.address`
object, the appropriate value will be inferred.

=== `set_option(self, opt: string, val)`

Set an option on the acceptor.

Currently available options are:

`"reuse_address"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/reuse_address.html[Check
Boost.Asio documentation].

`"enable_connection_aborted"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/enable_connection_aborted.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the acceptor.

Currently available options are:

`"reuse_address"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/reuse_address.html[Check
Boost.Asio documentation].

`"enable_connection_aborted"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/enable_connection_aborted.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

=== `bind(self, addr: ip.address|string, port: number)`

Bind the acceptor to the given local endpoint.

=== `listen(self [, backlog: number])`

Place the acceptor into the state where it will listen for new connections.

`backlog` is the maximum length of the queue of pending connections. If not
provided, an implementation defined maximum length will be used.

=== `accept(self) -> ip.tcp.socket`

Initiate an accept operation and blocks current fiber until it completes or
errs.

=== `close(self)`

Close the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_socket_acceptor/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous accept operations will be cancelled immediately.

A subsequent call to open() is required before the acceptor can again be used to
again perform socket accept operations.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_socket_acceptor/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error.
____

== Properties

=== `is_open: boolean`

Whether the acceptor is open.

=== `local_address: ip.address`

The local address endpoint of the acceptor.

=== `local_port: number`

The local port endpoint of the acceptor.
