= ip.udp.socket

ifeval::["{doctype}" == "manpage"]

== Name

Emilua - Lua execution engine

== Synopsis

endif::[]

[source,lua]
----
local sock = ip.udp.socket.new()
sock.open('v4')
sock:bind(ip.address.any_v4(), 1234)

local buf = byte_span.new(1024)
local nread, remote_addr, remote_port = sock:receive_from(buf)
sock:send_to(buf:slice(1, nread), remote_addr, remote_port)
----

== Functions

=== `new() -> ip.udp.socket`

Constructor.

=== `open(self, address_family: "v4"|"v6"|ip.address)`

Open the socket.

`address_family` can be either `"v4"` or `"v6"`. If you provide an `ip.address`
object, the appropriate value will be inferred.

=== `bind(self, addr: ip.address|string, port: integer)`

Bind the socket to the given local endpoint.

=== `shutdown(self, what: "receive"|"send"|"both")`

Disable sends or receives on the socket.

`what` can be one of the following:

`"receive"`:: Shutdown the receive side of the socket.
`"send"`:: Shutdown the send side of the socket.
`"both"`:: Shutdown both send and receive on the socket.

NOTE: Doing this only mutates the socket object, but nothing will be sent over
the wire. It could be useful if you're planning to send the FD around to other
processes.

=== `connect(self, addr: ip.address, port: integer)`

Set the default destination address so datagrams can be sent using `send()`
without specifying a destination address.

=== `disconnect(self)`

Dissolve the socket's association by resetting the socket's peer address
(i.e. connect(3) will be called with an `AF_UNSPEC` address).

=== `close(self)`

Close the socket.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_datagram_socket/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous send, receive or connect operations will be cancelled
immediately, and will complete with the `boost::asio::error::operation_aborted`
error.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_datagram_socket/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error.
____

=== `assign(self, address_family: "v4"|"v6"|ip.address, fd: file_descriptor)`

Assign an existing native socket to `self`.

`address_family` can be either `"v4"` or `"v6"`. If you provide an `ip.address`
object, the appropriate value will be inferred.

=== `release(self) -> file_descriptor`

Release ownership of the native descriptor implementation.

Forward the call to
https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/reference/basic_datagram_socket/release/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error. Ownership of the
native socket is then transferred to the caller.
____

=== `receive(self, buffer: byte_span[, flags: integer]) -> integer`

Receive a datagram and blocks current fiber until it completes or errs.

Returns the number of bytes read.

`flags` is `0` or an or-combination of values from
xref:ip.message_flag.adoc[ip.message_flag(3em)].

=== `receive_from(self, buffer: byte_span[, flags: integer]) -> integer, ip.address, integer`

Receive a datagram and blocks current fiber until it completes or errs.

Returns the number of bytes read plus the endpoint (address {plus} port) of the
remote sender of the datagram.

`flags` is `0` or an or-combination of values from
xref:ip.message_flag.adoc[ip.message_flag(3em)].

=== `send(self, buffer: byte_span[, flags: integer]) -> integer`

Send data on the datagram socket and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

`flags` is `0` or an or-combination of values from
xref:ip.message_flag.adoc[ip.message_flag(3em)].

NOTE: The `send` operation can only be used with a connected socket. Use the
`send_to` function to send data on an unconnected datagram socket.

=== `send_to(self, buffer: byte_span, remote_addr: ip.address, remote_port: integer[, flags: integer]) -> integer`

Send a datagram to the specified remote endpoint and blocks current fiber until
it completes or errs.

Returns the number of bytes written.

`flags` is `0` or an or-combination of values from
xref:ip.message_flag.adoc[ip.message_flag(3em)].

=== `set_option(self, opt: string, val)`

Set an option on the socket.

Currently available options are:

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"broadcast"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/broadcast.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"reuse_address"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/reuse_address.html[Check
Boost.Asio documentation].

`"multicast_loop"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_enable_loopback.html[Check
Boost.Asio documentation].

`"multicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_hops.html[Check
Boost.Asio documentation].

`"join_multicast_group"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_join_group.html[Check
Boost.Asio documentation].

`"leave_multicast_group"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_leave_group.html[Check
Boost.Asio documentation].

`"multicast_interface"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_outbound_interface.html[Check
Boost.Asio documentation].

`"unicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_unicast%5F_hops.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the socket.

Currently available options are:

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"broadcast"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/broadcast.html[Check
Boost.Asio documentation].

`"do_not_route"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/do_not_route.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

`"reuse_address"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/reuse_address.html[Check
Boost.Asio documentation].

`"multicast_loop"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_enable_loopback.html[Check
Boost.Asio documentation].

`"multicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_multicast%5F_hops.html[Check
Boost.Asio documentation].

`"unicast_hops"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_unicast%5F_hops.html[Check
Boost.Asio documentation].

`"v6_only"`::
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/ip%5F_v6_only.html[Check
Boost.Asio documentation].

=== `io_control(self, command: string[, ...])`

Perform an IO control command on the socket.

Currently available commands are:

`"bytes_readable"`:: Expects no arguments. Get the amount of data that can be
read without blocking. Implements the `FIONREAD` IO control command.

== Properties

=== `is_open: boolean`

Whether the socket is open.

=== `local_address: ip.address`

The local address endpoint of the socket.

=== `local_port: integer`

The local port endpoint of the socket.

=== `remote_address: ip.address`

The remote address endpoint of the socket.

=== `remote_port: integer`

The remote port endpoint of the socket.
