= pipe.read_stream

ifeval::["{doctype}" == "manpage"]

== Name

Emilua - Lua execution engine

endif::[]

== Functions

=== `new() -> pipe.read_stream`

[source,lua]
----
new()                    -- <1>
new(fd: file_descriptor) -- <2>
----
<1> Default constructor.
<2> Converts a file descriptor into a pipe end.

=== `close(self)`

Close the pipe.

Forward the call to
https://www.boost.org/doc/libs/1_79_0/doc/html/boost_asio/reference/basic_readable_pipe/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous read operations will be cancelled immediately, and will
complete with the `boost::asio::error::operation_aborted` error.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the pipe.

Forward the call to
https://www.boost.org/doc/libs/1_79_0/doc/html/boost_asio/reference/basic_readable_pipe/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous read operations to finish
immediately, and the handlers for cancelled operations will be passed the
`boost::asio::error::operation_aborted` error.
____

=== `assign(self, fd: file_descriptor)`

Assign an existing native pipe to `self`.

=== `release(self) -> file_descriptor`

Release ownership of the native descriptor implementation.

Forward the call to
https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/reference/basic_readable_pipe/release/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous read operations to finish
immediately, and the handlers for cancelled operations will be passed the
`boost::asio::error::operation_aborted` error. Ownership of the native pipe is
then transferred to the caller.
____

=== `read_some(self, buffer: byte_span) -> number`

Read data from the pipe and blocks current fiber until it completes or errs.

Returns the number of bytes read.

== Properties

=== `is_open: boolean`

Whether the pipe is open.
