= serial_port

ifeval::["{doctype}" == "manpage"]

== Name

Emilua - Lua execution engine

== Synopsis

endif::[]

[source,lua]
----
local port = serial_port.new()
port:open(name)
----

== Functions

=== `new() -> serial_port`

Constructor.

=== `open(self, device: string)`

Open the serial port using the specified device name.

`device` is something like `"COM1"` on Windows, and `"/dev/ttyS0"` on POSIX
platforms.

=== `close(self)`

Close the port.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_serial_port/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous read or write operations will be cancelled immediately, and
will complete with the `boost::asio::error::operation_aborted` error.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_serial_port/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous read or write operations to
finish immediately, and the handlers for cancelled operations will be passed the
`boost::asio::error::operation_aborted` error.
____

=== `send_break(self)`

Send a break sequence to the serial port.

This function causes a break sequence of platform-specific duration to be sent
out the serial port.

=== `read_some(self, buffer: byte_span) -> number`

Read data from the port and blocks current fiber until it completes or errs.

Returns the number of bytes read.

=== `write_some(self, buffer: byte_span) -> number`

Write data to the port and blocks current fiber until it completes or errs.

Returns the number of bytes written.

== Properties

=== `is_open: boolean`

Whether the port is open.

=== `baud_rate: number`

Read or write current baud rate setting.

=== `flow_control: string`

Read or write current flow control setting.

It can be one of:

* `"none"`.
* `"software"`.
* `"hardware"`.

=== `parity: string`

Read or write current parity setting.

It can be one of:

* `"none"`.
* `"odd"`.
* `"even"`.

=== `stop_bits: string`

Read or write current stop bit width setting.

It can be one of:

* `"one"`.
* `"one_point_five"`.
* `"two"`.

=== `character_size: number`

Read or write current character size setting.
