= unix.datagram_socket

ifeval::["{doctype}" == "manpage"]

== Name

Emilua - Lua execution engine

== Synopsis

endif::[]

[source,lua]
----
local sock = unix.datagram_socket.new()
sock.open()
sock.bind('/tmp/9Lq7BNBnBycd6nxy.socket')

local buf = byte_span.new(1024)
local nread = sock:receive(buf)
print(buf:slice(1, nread))
----

== Functions

=== `new() -> unix.datagram_socket`

[source,lua]
----
new()                    -- <1>
new(fd: file_descriptor) -- <2>
----
<1> Default constructor.
<2> Converts a file descriptor into an `unix.datagram_socket` object.

=== `pair() -> unix.datagram_socket, unix.datagram_socket`

Create a pair of connected sockets.

=== `open(self)`

Open the socket.

=== `bind(self, pathname: string)`

Bind the socket to the given local endpoint.

=== `connect(self, pathname: string)`

Set the default destination address so datagrams can be sent using `send()`
without specifying a destination address.

=== `disconnect(self)`

Dissolve the socket's association by resetting the socket's peer address
(i.e. connect(3) will be called with an `AF_UNSPEC` address).

=== `close(self)`

Close the socket.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_datagram_socket/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous send, receive or connect operations will be cancelled
immediately, and will complete with the `boost::asio::error::operation_aborted`
error.
____

=== `shutdown(self, what: string)`

Disable sends or receives on the socket.

`what` can be one of the following:

`"receive"`:: Shutdown the receive side of the socket.
`"send"`:: Shutdown the send side of the socket.
`"both"`:: Shutdown both send and receive on the socket.

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/reference/basic_datagram_socket/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error.
____

=== `assign(self, fd: file_descriptor)`

Assign an existing native socket to `self`.

=== `release(self) -> file_descriptor`

Release ownership of the native descriptor implementation.

Forward the call to
https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/reference/basic_datagram_socket/release/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error. Ownership of the
native socket is then transferred to the caller.
____

=== `receive(self, buffer: byte_span[, flags: integer]) -> integer`

Receive a datagram and blocks current fiber until it completes or errs.

Returns the number of bytes read.

`flags` is `0` or an or-combination of values from
xref:unix.message_flag.adoc[unix.message_flag(3em)].

=== `receive_from(self, buffer: byte_span[, flags: integer]) -> integer, string`

Receive a datagram and blocks current fiber until it completes or errs.

Returns the number of bytes read plus the pathname of the
remote sender of the datagram.

`flags` is `0` or an or-combination of values from
xref:unix.message_flag.adoc[unix.message_flag(3em)].

=== `send(self, buffer: byte_span[, flags: integer]) -> integer`

Send data on the datagram socket and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

`flags` is `0` or an or-combination of values from
xref:unix.message_flag.adoc[unix.message_flag(3em)].

NOTE: The `send` operation can only be used with a connected socket. Use the
`send_to` function to send data on an unconnected datagram socket.

=== `send_to(self, buffer: byte_span, pathname: string[, flags: integer]) -> integer`

Send a datagram to the specified remote endpoint and blocks current fiber until
it completes or errs.

Returns the number of bytes written.

`flags` is `0` or an or-combination of values from
xref:unix.message_flag.adoc[unix.message_flag(3em)].

=== `receive_with_fds(self, buffer: byte_span, maxfds: integer) -> integer, file_descriptor[]`

Receive a datagram and blocks current fiber until it completes or errs.

Returns the number of bytes read plus the table containing the `fds` read.

=== `receive_from_with_fds(self, buffer: byte_span, maxfds: integer) -> integer, string, file_descriptor[]`

Receive a datagram and blocks current fiber until it completes or errs.

Returns the number of bytes read plus the pathname of the remote sender of the
datagram plus the table containing the `fds` read.

=== `send_with_fds(self, buffer: byte_span, fds: file_descriptor[]) -> integer`

Send data on the datagram socket and blocks current fiber until it completes or
errs.

Returns the number of bytes written.

NOTE: The `send` operation can only be used with a connected socket. Use the
`send_to` function to send data on an unconnected datagram socket.

=== `send_to_with_fds(self, buffer: byte_span, pathname: string, fds: file_descriptor[]) -> integer`

Send a datagram to the specified remote endpoint and blocks current fiber until
it completes or errs.

Returns the number of bytes written.

=== `set_option(self, opt: string, val)`

Set an option on the socket.

Currently available options are:

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the socket.

Currently available options are:

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

`"send_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/send_buffer_size.html[Check
Boost.Asio documentation].

`"receive_buffer_size"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/receive_buffer_size.html[Check
Boost.Asio documentation].

=== `io_control(self, command: string[, ...])`

Perform an IO control command on the socket.

Currently available commands are:

`"bytes_readable"`:: Expects no arguments. Get the amount of data that can be
read without blocking. Implements the `FIONREAD` IO control command.

== Properties

=== `is_open: boolean`

Whether the socket is open.

=== `local_path: string`

The local address endpoint of the socket.

=== `remote_path: string`

The remote address endpoint of the socket.
