= unix.seqpacket_acceptor

ifeval::["{doctype}" == "manpage"]

== Name

Emilua - Lua execution engine

== Synopsis

endif::[]

[source,lua]
----
local a = unix.seqpacket_acceptor.new()
a:open()
a:bind('/tmp/9Lq7BNBnBycd6nxy.socket')
a:listen()

while true do
    local s = a:accept()
    spawn(function()
        my_client_handler(s)
    end)
end
----

== Functions

=== `new() -> unix.seqpacket_acceptor`

Constructor.

=== `open(self)`

Open the acceptor.

=== `set_option(self, opt: string, val)`

Set an option on the acceptor.

Currently available options are:

`"enable_connection_aborted"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/enable_connection_aborted.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the acceptor.

Currently available options are:

`"enable_connection_aborted"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/enable_connection_aborted.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

=== `bind(self, pathname: string)`

Bind the acceptor to the given local endpoint.

=== `listen(self [, backlog: number])`

Place the acceptor into the state where it will listen for new connections.

`backlog` is the maximum length of the queue of pending connections. If not
provided, an implementation defined maximum length will be used.

=== `accept(self) -> unix.seqpacket_protocol.socket`

Initiate an accept operation and blocks current fiber until it completes or
errs.

=== `close(self)`

Close the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_socket_acceptor/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous accept operations will be cancelled immediately.

A subsequent call to open() is required before the acceptor can again be used to
again perform socket accept operations.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_socket_acceptor/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error.
____

== Properties

=== `is_open: boolean`

Whether the acceptor is open.

=== `local_path: string`

The local address of the acceptor.
