= emilua(1)
Vinícius dos Santos Oliveira
{VERSION}
:doctype: manpage
:mansource: Emilua {VERSION}
:manmanual: General Commands Manual

== NAME

Emilua - Lua execution engine

== SYNOPSIS

*emilua* [_OPTION_]... _SCRIPT_FILE_ +
*emilua* -h|--help +
*emilua* --version

== DESCRIPTION

Emilua glues a LuaJIT interpreter to the Boost.Asio execution engine by exposing
fiber and async IO APIs. It also allows multiple Lua VMs to share the same
execution context and to communicate with each other through actor-inspired
APIs. Threading capabilities are also exposed. In short, Emilua is a complete
execution engine for Lua.

== OPTIONS

*--main-context-concurrency-hint* _HINT_::

  Use _HINT=1_ to inform *spawn_ctx_threads()* won't be called from the main
  execution context and enable a few optimisations. Recompile Emilua with the
  proper configure flags to enable even more aggressive optimizations. Check
  <https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/overview/core/concurrency_hint.html>
  for more info.

*-h, --help*::

  Show help and exit.

*--version*::

  Show version and exit.

== ENVIRONMENT

EMILUA_COLORS=_ON|1|YES|TRUE_::

  Disable colour support auto-detection and force colour output on log messages.

EMILUA_COLORS=_OFF|0|NO|FALSE_::

  Disable colour support on log messages altogether.

EMILUA_PATH::

  A colon-separated list of directories to augment the default search path for
  modules. The modules from this search set have higher priority than the ones
  in the default search path. On Windows, the list is semicolon-separated.
