= Alternative projects

:toc: macro
:_:
:cpp: C++

toc::[]

== https://github.com/wahern/cqueues[cqueues]

* Designed “to be unintrusive, composable, and embeddable within existing
  applications” [sic].
* Coroutines.
* No fibers.
* No actors.

== https://www.tarantool.io/en/doc/2.1/reference/reference_lua/fiber/[Tarantool's fibers]

* Fibers.
* https://www.tarantool.io/en/doc/2.1/reference/reference_lua/fiber/#fiber-testcancel[Fiber
  interruption API].
* https://www.tarantool.io/en/doc/2.1/reference/reference_lua/fiber/#fiber-object-storage[Fiber-local-storage].
* https://www.tarantool.io/en/doc/2.1/book/box/atomic/#atomic-implicit-yields[There
  is a builtin reactor to perform IO multiplexing (or at least the fiber
  behaviour can be understood using this model)].
* No actors.

== https://github.com/effil/effil[Effil]

* Threads.
* Threads communicate through messaging.
* No actors.
* No IO reactor.

== http://lualanes.github.io/lanes/[Lanes]

* Threads.
* No actors.
* No IO reactor.

== https://love2d.org/wiki/love.thread[Löve]

* Focused on game development.
* Threads.
* Threads communicate through messaging.
* No actors.
* No IO reactor.

== https://github.com/lefcha/concurrentlua[ConcurrentLua]

* It focuses on distributed actor model.
* Other models are left off (e.g. fibers).

== http://www.inf.puc-rio.br/~roberto/docs/ry08-05.pdf[luaproc]

* It has a primitive model of what could become a full actor system.
** It can work with a fixed number of worker threads.
** Spawns lua VMs.
** Lua VMs can migrate threads (work-stealing).
** With proper discipline, an actor system can be built on top (e.g. giving each
   lua process an unique name and using these string identifiers to create new
   channels and so on). It is at most an inconvenient that we don't have the
   desired semantics by default.
* It doesn't have a builtin reactor to perform IO multiplexing.
* No fibers.

== https://openresty.org/[OpenResty]

Most of the languages are not designed to make the programmer worry about memory
allocation failing. Lua is no different. If you want to deal with resource
exhaustion, C and {cpp} are the only good choices.

A web server written in lua exposed directly to the web is rarely a good idea as
it can't properly handle allocation failures or do proper resource management in
a few other areas.

OpenResty's core is a C application (nginx). The lua application that can be
written on top is hosted by this C runtime that is well aware of the
connections, the process resources and its relationships to each lua-written
handler. The runtime then can perform proper resource management. Lua is a mere
slave of this runtime, it doesn't really own anything.

This architecture works quite well while gives productivity to the web
application developer. Emilua can't just compete with OpenResty. Go for
OpenResty if you're doing an app exposed to the wide web.

Emilua can perform better for client apps that you deliver to customers. For
instance, you might develop a torrent client with Emilua and it would work
better than OpenResty. Emilua HTTP interface is also designed more like a
gateway interface, so we can, in the future, implement this interface as an
OpenResty lib to easily allow porting apps over.

* Emilua can also be used behind a proper server.
* Emilua can be used to quickly prototype the architecture of apps to be written
  later in {cpp} using an API that resembles Boost.Asio a lot (and
  https://github.com/blinktrade/iofiber[IOFiber] will bring them even closer).
* In the future, Emilua will be able to make use of native plug-ins so you can
  offload much of the resource management.
* Emilua apps can do some level of resource (under)management by restricting the
  number of connections/fibers/...
* Emilua won't be that bad given its defaults (active async style, no implicit
  write buffer to deal with concurrent writes, many abstractions designed with
  back-pressure in mind, ...).
* The actor model opens up some possibilities for Emilua's future
  (e.g. partition your app resources among multiple VMs and feel free to kill
  the bad VMs).

== NodeJS wannabes

When you create a project that tries to bring together the best of two worlds,
you're also actually bringing together the worst of two worlds. This sums up
most of the attempts to mirror NodeJS API (and I'm not free of guilty here as
this includes a former {cpp} project of
mine{_}footnote:[https://github.com/vinipsmaker/tufao]).

* If everything is implemented correctly, it can only achieve being as bad as
  NodeJS is.
* Passive async style that matches up badly with back-pressure.

=== https://luvit.io/[Luvit]

* No fibers.
* No actors.

=== https://github.com/ignacio/LuaNode[LuaNode]

* No fibers.
* No threads.

=== https://github.com/lipp/nodish[nodish]

* No fibers.
* No threads.
